ALTER TABLE funds ADD COLUMN market TEXT NOT NULL DEFAULT 'CN_FUND';
ALTER TABLE funds ADD COLUMN currency TEXT NOT NULL DEFAULT 'CNY';

ALTER TABLE transactions ADD COLUMN price REAL NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN currency TEXT NOT NULL DEFAULT 'CNY';
ALTER TABLE transactions ADD COLUMN fx_rate REAL NOT NULL DEFAULT 1;