ALTER TABLE funds ADD COLUMN management_fee REAL NOT NULL DEFAULT 0;
ALTER TABLE funds ADD COLUMN custody_fee REAL NOT NULL DEFAULT 0;
ALTER TABLE funds ADD COLUMN subscription_fee REAL NOT NULL DEFAULT 0;
ALTER TABLE funds ADD COLUMN redemption_fee_tiers TEXT NOT NULL DEFAULT '[]';